### ISSUE TITLE
il.js:109 Uncaught TypeError: Cannot read properties of undefined (reading 'NODE_DEBUG')  

### ISSUE THREAD

**Issue by wade-liwei** [InjectiveLabs/injective-dex#1004]
how to resolve the problem?
![image](https://github.com/InjectiveLabs/injective-dex/assets/49429891/bbf61fa0-ba16-4acb-9d88-a5d62afcce02)

**Comment by bangjelkoski** [comment]
Read more on dApps configuration here -> https://github.com/InjectiveLabs/injective-ts/wiki/08BuildingDapps
