### ISSUE TITLE
[Market] Support for expired TEF markets

### ISSUE THREAD

**Issue by gorgos** [InjectiveLabs/injective-dex#101]
Right now when a market expires, there is no support from the DEX for this. When a user is on the page while the market expires, nothing happens in the UI. And when refreshing the site, the market is not found anymore.

Maybe @maximshen007 has some suggestions for how to handle this case?

But a simple solution would just be keeping the market page alive with a big notification its expired and all buttons being disabled.

**Comment by gorgos** [comment]
@bangjelkoski accidental closing?

**Comment by bangjelkoski** [comment]
No, its done.
