### ISSUE TITLE
bridge eth/inj

### ISSUE THREAD

**Issue by Gerrypitt123** [InjectiveLabs/injective-dex#1013]
Hi 
I bridged a token from ETH o INJ using the steps adviced here:
https://blog.injective.com/en/how-to-bridge-from-ethereum-to-injective-using-metamask/

The bridged went successfully, however now I cant trade/swap/find the new token on the metamask wallet, for reference the token is SDEX and the below is the INJ reference

https://explorer.injective.network/transaction/0x8a52f2308ccfc3ad798ed8c8ad65a7257ce83221b9013352176ee3f52553ba47/

any help is appreciated, i would like to be able to check and swap the token in my wallet.

**Comment by bangjelkoski** [comment]
SDEX is not supported for trading on Injective as of right now.
