### ISSUE TITLE
"Trading Rules" table for tick sizes

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#238]
Discussing tick sizes with @maximshen007 he thinks we should also have a table like the below down the line which is great.

![image](https://user-images.githubusercontent.com/83584143/131038634-448f17d1-83f4-4f21-9714-15409a7b592b.png)

https://www.binance.com/en/trade-rule

Certainly not a priority, we can put to glacier for now.

**Comment by bangjelkoski** [comment]
We have these on the explorer now.
