### ISSUE TITLE
[Market] Minimum price increments for orderbook aggregation

### ISSUE THREAD

**Issue by bangjelkoski** [InjectiveLabs/injective-dex#28]
Add support for order book aggregation based on minimum price increments. 
![image](https://user-images.githubusercontent.com/15016904/122349027-1adbab00-cf4c-11eb-8585-443e6ae5d00c.png)

**Comment by achilleas-kal** [comment]
Hey @ThomasRalee I noticed we sometimes roundup the numbers depending on the decimals so I managed to replicate two cases..to a trader this looks like a huge bug as the "orders are not being matched" but it's actually related to the rounding.

The bid (buy) orders should always have a lower price than the ask (sell orders), if they cross then that means they should have been filled. We should never see buy and sell orders at exactly the same price in the orderbook.

![image](https://user-images.githubusercontent.com/83584143/141288761-9fbde75a-09ff-4ebc-9491-008c457c5583.png)


![image](https://user-images.githubusercontent.com/83584143/141288314-fcdccae5-4693-49e4-abc8-c2644ac01dfc.png)
