### ISSUE TITLE
Support for negative maker fees

### ISSUE THREAD

**Issue by gorgos** [InjectiveLabs/injective-dex#280]
![image](https://user-images.githubusercontent.com/659390/132757094-cf1669f5-d552-4beb-bf4c-014159292a7e.png)

The tooltip is obviously not correct for a negative maker fee market which you can see at https://devnet-dex.injective.dev/spot/inj-usdt/. Maybe something like 'If your limit order doesn't get filled as a taker order, you will receive a fee refund of x'

In above example the market the maker fee should be -0.1%, so x = 0.06 USDT.

**Comment by bangjelkoski** [comment]
I've added the Est. Rebate field and I'll close the issue but we have to discuss and decide what and when to show from a product standpoint.
