### ISSUE TITLE
[Market] Can send market order using quoteAssetQty

### ISSUE THREAD

**Issue by maximshen007** [InjectiveLabs/injective-dex#288]
right now, injective.exchange can only place order in the quantities of base asset, however, we need to be able to have traders do both to improve the user experience like FTX does

![FTX_market_order](https://user-images.githubusercontent.com/77034976/134068079-d8c53a50-2c00-45db-b5ab-cc4d9dd80f99.png)

select makert order as order type on https://ftx.com/trade/BTC/USDT

It is handy to allow trader send market order on both spot and perp markets. FTX for example, they allow traders to change either base qty or quote qty, and UI automatically changes the qty needed for the other asset in the pair.

**Comment by shane-moore** [comment]
hi @achilleas-kal, is this what you were imagining for a dropdown?
<img width="1010" alt="Screen Shot 2022-02-13 at 2 00 33 PM" src="https://user-images.githubusercontent.com/41407272/153777244-270f4d7f-b947-40b3-966b-907006748585.png">

Another option would be to go with selecting between Amount/Total like Binance does:
<img width="1023" alt="Screen Shot 2022-02-13 at 2 00 17 PM" src="https://user-images.githubusercontent.com/41407272/153777284-e8eb6508-0d21-47d9-a81d-1bacfa1156a3.png">

Tagging @maximshen007 and @bangjelkoski for any additional input.  I'm happy to build it either way, or in another fashion if one comes to mind

**Comment by achilleas-kal** [comment]
Hey @shane-moore I think it makes more sense to:

1) Show the "arrow (^)" in your implementation next to the already existing denom
2) Users can click on that to switch from INJ to USDT and vice versa

Saves some space and it's generally better in my opinion - so it would be implemented here for instance. I'd also make the font/boxes a bit smaller.

![image](https://user-images.githubusercontent.com/83584143/153777628-eb48ba1a-13cb-43e7-a537-c6eb8dd5b3d2.png)

**Comment by bangjelkoski** [comment]
> hi @achilleas-kal, is this what you were imagining for a dropdown? <img alt="Screen Shot 2022-02-13 at 2 00 33 PM" width="1010" src="https://user-images.githubusercontent.com/41407272/153777244-270f4d7f-b947-40b3-966b-907006748585.png">
> 
> Another option would be to go with selecting between Amount/Total like Binance does: <img alt="Screen Shot 2022-02-13 at 2 00 17 PM" width="1023" src="https://user-images.githubusercontent.com/41407272/153777284-e8eb6508-0d21-47d9-a81d-1bacfa1156a3.png">
> 
> Tagging @maximshen007 and @bangjelkoski for any additional input. I'm happy to build it either way, or in another fashion if one comes to mind

We haven't had a product discussion about this yet, UI changes should be done after we are finished with the current overhaul we are working on as it introduced tons of codebase changes.
