### ISSUE TITLE
[History] List of historical Funding Payments

### ISSUE THREAD

**Issue by bangjelkoski** [InjectiveLabs/injective-dex#310]

**Comment by achilleas-kal** [comment]
The API is already implemented for this, included in the API docs/tested: https://api.injective.exchange/#injectivederivativeexchangerpc-fundingpayments

**Comment by bangjelkoski** [comment]
Nice, thanks for the heads up

**Comment by shane-moore** [comment]
@achilleas-kal, the `fundingpayments` api responds with the quote asset amount and timestamp.  Here is a mockup if we went with option 1 and added a "Funding History" tab for perpetual markets:
![Screen Shot 2022-02-18 at 7 47 16 PM](https://user-images.githubusercontent.com/41407272/154781305-b2aaa5b2-0860-47ec-ae6b-cabcc7663a80.png)

 https://github.com/InjectiveLabs/injective-dex/issues/259 mentions to include additional columns, and I believe that would take api work.
I understand the current priority is the dex overhaul, and I am happy to have a product discussion about this feature afterwards.

**Comment by achilleas-kal** [comment]
This feature has been implemented.
