### ISSUE TITLE
OB Colors change on certain actions

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#324]
The red on the sells becomes darker when certain actions are triggered but that doesn't happen on the buy side.

![image](https://user-images.githubusercontent.com/83584143/138564914-b5316ebb-4039-46e1-83dc-cbbea7cd34c9.png)

![image](https://user-images.githubusercontent.com/83584143/138564919-9253ab3e-f892-4e2d-85b1-f105e1fecb16.png)

**Comment by bangjelkoski** [comment]
This is resolved, I've removed the transforms that might have caused this. If this persists, please enable Hardware acceleration on your browser.
