### ISSUE TITLE
Order execution modal

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#334]
This prompt should only show if my order crosses the opposite side.
![image](https://user-images.githubusercontent.com/83584143/140315849-db6a30fb-f3fa-4b18-bd6f-b02302079f52.png)

**Comment by bangjelkoski** [comment]
I can't reproduce.

![image](https://user-images.githubusercontent.com/15016904/140643558-562799c5-f353-4cf1-8282-42954b78aa7b.png)
