### ISSUE TITLE
Hide discounts for markets with negative maker fees

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#338]
This should be hidden if the market has negative maker fees
![image](https://user-images.githubusercontent.com/83584143/140433066-e69d86a4-dcd0-416b-8929-00a7cc7f633b.png)

**Comment by achilleas-kal** [comment]
Still evident for markets with negative maker fees, also the "fee" is with a discount.

![image](https://user-images.githubusercontent.com/83584143/140612345-8d91d8ae-13f8-4558-a76f-cc7219a8a0fb.png)

**Comment by bangjelkoski** [comment]
I don't see a reason it should be without a discount. That information is meaningless to the user. 

Resolved the other issue.
