### ISSUE TITLE
Cancel All - Portfolio

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#340]
The Cancel All button in the portfolio isn't working, I signed the message but the orders don't get cancelled. That's an issue only in derivatives, spot orders are cancelled. However, when I cancel all my spot orders I need to refresh the page to see them disappear

**Comment by achilleas-kal** [comment]
Derivative orders are fixed and they disappear immediately but I still need to refresh for the spot orders to disappear.

![image](https://user-images.githubusercontent.com/83584143/140589540-862bcb22-785c-48e2-af94-6adf4ba39f6c.png)

**Comment by ThomasRalee** [comment]
Just tested `Cancel All` on Devnet, seems that the spot orders streaming is working hence flushing the spot order table after clicking on the `Cancel All` button hence resolving this issue.  

@achilleas-kal, can you please verify again and close this ticket if's been resolved?

**Comment by bangjelkoski** [comment]
> Just tested `Cancel All` on Devnet, seems that the spot orders streaming is working hence flushing the spot order table after clicking on the `Cancel All` button.
> 
> @achilleas-kal, can you please verify again and close this ticket if's been resolved?

We can close the issue and it can be reopened (or open a new one) if it happens again.
