### ISSUE TITLE
Tabs default to open positions as the OB replenishes

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#342]
From a community member "everytime the screen/quotes refresh, my bottom window will change to Open Positions by itself, no matter if I was Open Orders or Trade History, makes it very frustrating when trying to look at trade history".

I can't replicate on devnet but if it's indeed an issue on mainnet I agree we should fix.

**Comment by bangjelkoski** [comment]
It's because he has an open position. I'll remove this on page load.

**Comment by achilleas-kal** [comment]
Yeah I tried on devnet with an open position but I couldn't replicate. Cool thanks!
