### ISSUE TITLE
Est. Fee Rebate Value

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#344]
The value should reflect the rebate I'll get after the relayer fees, for instance here I'd get 3k USDT opposed to 5k USDT.
![image](https://user-images.githubusercontent.com/83584143/140511135-6cef3ab9-0888-4661-9e5b-7910cfa392e0.png)

**Comment by bangjelkoski** [comment]
> The value should reflect the rebate I'll get after the relayer fees, for instance here I'd get 3k USDT opposed to 5k USDT. ![image](https://user-images.githubusercontent.com/83584143/140511135-6cef3ab9-0888-4661-9e5b-7910cfa392e0.png)

Does this imply we are only "returning" the 60% of the fees as a rebate for negative maker fee rate?

**Comment by achilleas-kal** [comment]
Yes
