### ISSUE TITLE
[Devnet] Alignment bug on derivatives 

### ISSUE THREAD

**Issue by albertchon** [InjectiveLabs/injective-dex#348]
Happens when resizing the window 
![image](https://user-images.githubusercontent.com/20461629/140611690-52690ef3-ea91-47ef-8f01-235d5744d0c4.png)

**Comment by achilleas-kal** [comment]
Happens in my 24' screen as well, without resizing. It's from a quite recent change wasn't there 1-2 days ago.
![image](https://user-images.githubusercontent.com/83584143/140612308-3e8040d1-2b15-4e2d-b6b4-2ecb701b307a.png)
