### ISSUE TITLE
Initial Margin validation

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#363]
Hey @bangjelkoski a user is not able to place a market buy order with an error on a markPrice validation.

See: https://www.loom.com/share/2504120f576b4636adc8c0e65fba989d

**Comment by achilleas-kal** [comment]
Re-opening this issue since we found that it's indeed FE validation.

**Comment by bangjelkoski** [comment]
> Re-opening this issue since we found that it's indeed FE validation.

Its not -> https://github.com/InjectiveLabs/injective-exchange/issues/221
