### ISSUE TITLE
Chart Settings

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#369]
1. The timeframes (in blue) don't work as expected, 1 day is actually 5 minutes and 1 week is 15m.
2. The countdown (in red) doesn't work as expected either, I'm in a 5 minute timeframe and after it resets to 04:59 it then resets again at around 04:00 so after 1 minute and not 5.

Can we do something about these issues or it's on TradingView?

![image](https://user-images.githubusercontent.com/83584143/141335322-acfe949b-b22a-4ede-9178-aa400cebb703.png)

**Comment by cmhchoi** [comment]
For 1), I don't think it's an error

The "1d 1w 1m 3m" at the bottom is the range of the timeline, where as the x-axis scale of 5m or 15m is actually the top left hand corner

**Comment by cmhchoi** [comment]
For 2), I cannot replicate it and I don't think we have control over this (it's Trading View)

**Comment by cmhchoi** [comment]
Added `invalid` label for now to prevent this being picked up by FE team

**Comment by achilleas-kal** [comment]
> The "1d 1w 1m 3m" at the bottom is the range of the timeline, where as the x-axis scale of 5m or 15m is actually the top left hand corner

The 1d 1w 1m 3m are not working as expected.

All the issues are shown in the video below, please refer to the points above as you watch the video.

https://www.loom.com/share/cd9596bd90474a3a9c4e7ca913456305

**Comment by cmhchoi** [comment]
I don't see the problem on production. Maybe devnet has lack of data and messed up Trading View?

**Comment by achilleas-kal** [comment]
I checked Mainnet, looks like issue one doesn't happen there which is weird but we still have an issue with the countdown. If you set it to 5m on Mainnet after it ends, it just disappears.

![image](https://user-images.githubusercontent.com/83584143/142767004-3817c6c8-88be-47ea-8298-06d5c2fdee6d.png)

![image](https://user-images.githubusercontent.com/83584143/142767010-5771c2d8-dbf3-435d-b618-f6a2a57008da.png)

**Comment by bangjelkoski** [comment]
> I checked Mainnet, looks like issue one doesn't happen there which is weird but we still have an issue with the countdown. If you set it to 5m on Mainnet after it ends, it just disappears.
> 
> ![image](https://user-images.githubusercontent.com/83584143/142767004-3817c6c8-88be-47ea-8298-06d5c2fdee6d.png)
> 
> ![image](https://user-images.githubusercontent.com/83584143/142767010-5771c2d8-dbf3-435d-b618-f6a2a57008da.png)

I don't think we can do anything here as we are using this as a library, so it can be an issue on their end that they have to resolve.
