### ISSUE TITLE
Subaccount Holdings

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#373]
Hi guys, a community member reported that he can't see the subaccount holdings he has on the DEX even though he just bought tokens.

They are visible though from the explorer.

![image](https://user-images.githubusercontent.com/83584143/141643726-5b86aa76-8eb2-412e-93f3-b42d9cef5609.png)

![image](https://user-images.githubusercontent.com/83584143/141643738-46478725-e76e-4f0d-9c70-30d53c3fcc37.png)

**Comment by bangjelkoski** [comment]
I can't reproduce this :| Reopen if someone else reports this please, it works fine for me for `devnet/testnet/mainnet`. Maybe they just needed a refresh.
