### ISSUE TITLE
Fees are hidden for small amounts

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#386]
"so if I trade a 0.0001 size btc/usdt perp and the fee is showing as 0.0, there is no easy way for me to look somewhere to see what the missing decimals are?"

We should show the fees regardless of how low they are.

**Comment by bangjelkoski** [comment]
You can't trade a 0.0001 size on btc/usdt perp, the quantity tick size is 0.1

**Comment by achilleas-kal** [comment]
Yeah that's what I thought too.

![image](https://user-images.githubusercontent.com/83584143/142073472-b334eae6-c7f5-4b1a-abd1-db68b5e3828b.png)

![image](https://user-images.githubusercontent.com/83584143/142073501-6ed27d72-842a-482a-b32f-3a057c7235c6.png)

**Comment by achilleas-kal** [comment]
Also from one of our MMs (fees hidden here too)

![image](https://user-images.githubusercontent.com/83584143/142187772-a2b5d3bf-137e-4e49-8ca3-260aff4dec54.png)
