### ISSUE TITLE
The buffer should only work for INJ transfers

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#388]
Looks like the buffer keeps a small amount of any token the user is trying to transfer? For instance here I wasn't able to transfer the full amount of USDC, the buffer should only be there for INJ since otherwise it will be confusing.

![image](https://user-images.githubusercontent.com/83584143/142219485-db320c44-0bf2-46f2-ab88-9e0dbb15d4fe.png)

**Comment by bangjelkoski** [comment]
Nope, we only apply buffer for INJ
![image](https://user-images.githubusercontent.com/15016904/142241430-9265ded0-43dd-44fb-82c4-9af111bd617d.png)
