### ISSUE TITLE
When a new order is created, the "flash" animation is being shot on the wrong order

### ISSUE THREAD

**Issue by dyegonery** [InjectiveLabs/injective-dex#390]
When I add a new limit order on the orderbook, a "flash" animation is trigerred on the orderbook. The problem I'm seeing is, the flash animation is only trigerred on the first order of the market, not on the order that I recently included. 

For example: INJ/USDT

Sell Orders:
12.90
12.80
12.75

Buy Orders:
12.25
12.12
11.95

Then, I sent a sell order at 12.85. The animation should happen in the row created between the "12.90" and "12.80" orders. Instead, the animation is trigerred always on the "12.75" order.

**Comment by bangjelkoski** [comment]
Closed https://github.com/InjectiveLabs/injective-dex/pull/548
