### ISSUE TITLE
Rates/fees shouldn't change in markets with negative maker fees

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#392]
Rates/fees should stay constant in markets with negative maker fees, discounts are irrelevant here.

![image](https://user-images.githubusercontent.com/83584143/142259451-278f3652-60cf-4361-8391-c3bc60df8e1d.png)

**Comment by bangjelkoski** [comment]
@achilleas-kal can you explain a bit more please?

**Comment by achilleas-kal** [comment]
Yes, so discounts for both maker/taker are not applied in markets with negative maker fees so here I should see -0.1%/0.2%
