### ISSUE TITLE
Reward epoch countdown in seconds will be more exciting than current in days

### ISSUE THREAD

**Issue by maximshen007** [InjectiveLabs/injective-dex#396]
![Screenshot from 2021-11-17 20-01-09](https://user-images.githubusercontent.com/77034976/142333107-674a34d3-acbd-431f-b132-987e9fd67dfa.png)

**Comment by maximshen007** [comment]
I will leave it to Chris if we need to change it

**Comment by bangjelkoski** [comment]
@cmhchoi
