### ISSUE TITLE
Some instructions to indicate that traders need to make subaccount deposit first and they need to have INJ first as gas fee

### ISSUE THREAD

**Issue by maximshen007** [InjectiveLabs/injective-dex#397]
![image](https://user-images.githubusercontent.com/77034976/142333936-d7bcc202-f6c1-4e8f-a439-173cc4a19a52.png)

**Comment by dyegonery** [comment]
I made this suggestion before. I think the "subaccount" term is not very clear. You should try using "Trading Account", as it's something already used in a lot of other exchanges.

**Comment by maximshen007** [comment]
> I made this suggestion before. I think the "subaccount" term is not very clear. You should try using "Trading Account", as it's something already used in a lot of other exchanges.

I agree

**Comment by achilleas-kal** [comment]
You wouldn't need INJ since we have fee delegation for this message type too but @cmhchoi can help us with the terms and UI here.

**Comment by bangjelkoski** [comment]
I'm going to use Trading Account until we figure out a better and more intuitive way to share our users the knowledge about subaccounts and what do they represent.
