### ISSUE TITLE
Margin Hold

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#411]
Hey @bangjelkoski we had a few reports on issues that seem to be related because the FE doesn't pick the correct balance (i.e. my balance is reduced after certain actions like placing limit orders but that's not reflected in my subaccount balance and I try to place new orders with "MAX" amount).

1. ![image](https://user-images.githubusercontent.com/83584143/142641001-8215cb74-b344-467c-a707-ab175e50acfc.png)

2. ![image](https://user-images.githubusercontent.com/83584143/142641143-98a65f6f-8e45-41d4-9d7b-96c6738153e5.png)

**Comment by bangjelkoski** [comment]
We have to improve streaming. If the FE doesn't "reflect" balances it means that the streaming failed to stream the updates.

**Comment by bangjelkoski** [comment]
This should be fixes after recent upgrades to the streams.
