### ISSUE TITLE
Markets with negative maker fees (rates/points)

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#412]
Hey @bangjelkoski the maker fee rate changed to 0%, this should have been negative and not 0. Specifically - 0.2% as per the module state: **"maker_fee_rate": "-0.002000000000000000"**

Also reward points are still visible for maker, we should see 0 for maker points. See https://github.com/InjectiveLabs/injective-dex/issues/394

![image](https://user-images.githubusercontent.com/83584143/142657993-78f10ba2-c801-4ae4-86f5-8058d236604e.png)

**Comment by bangjelkoski** [comment]
This was the reason why I requested a detailed state about all of these values. In some previous issue, you requested to change the Maker rate fee to `0%` if some case is applied and now we have to change it again.
