### ISSUE TITLE
add depth chart

### ISSUE THREAD

**Issue by maximshen007** [InjectiveLabs/injective-dex#415]
every crypto exchange has a depth chart, it is useful for traders, especially UI traders to see the sell/buy pressure from the depth resting orders. 

![Screenshot from 2021-11-19 21-03-22](https://user-images.githubusercontent.com/77034976/142710662-3dcfe91b-103c-4661-9309-d89ae3330470.png)

**Comment by achilleas-kal** [comment]
Already in Glacier https://github.com/InjectiveLabs/injective-dex/issues/271
