### ISSUE TITLE
Show liquidations as separate execution type

### ISSUE THREAD

**Issue by gorgos** [InjectiveLabs/injective-dex#416]
![image](https://user-images.githubusercontent.com/659390/142714016-197297c6-2a34-472d-bfe0-3e80ec04436f.png)

Liquidations are currently shown as market orders which is technically correct, but showing it as liquidation is more precise. Also the tooltip for 'Execution Type' should be changed accordingly.

**Comment by bangjelkoski** [comment]
We only have these execution types right now: 

```
export declare enum TradeExecutionType {
    Market = "market",
    LimitFill = "limitFill",
    LimitMatchRestingOrder = "limitMatchRestingOrder",
    LimitMatchNewOrder = "limitMatchNewOrder"
}
```

How can we know if the position has been liquidated to actually show that label?

**Comment by gorgos** [comment]
@bangjelkoski There should be a flag `isLiquidation`: https://github.com/InjectiveLabs/injective-exchange/blob/022f294cc0d86286b77102eac2a7a22ebb389501/service/derivatives/derivatives_api.go#L394

**Comment by bangjelkoski** [comment]
Resolved https://github.com/InjectiveLabs/injective-dex/commit/af29754ddd568666f011b2600a80c502d6d9d7a4
