### ISSUE TITLE
Portfolio Trading Account Holdings not showing all the tokens

### ISSUE THREAD

**Issue by cmhchoi** [InjectiveLabs/injective-dex#419]
<img width="1368" alt="Screenshot 2021-11-22 at 1 27 34 AM" src="https://user-images.githubusercontent.com/9430957/142772615-4f2224f1-59d3-4dc2-8d82-994633742638.png">

Currently only showing INJ when other accounts have positive balances as well

**Comment by cmhchoi** [comment]
Seems like it's just a matter of slowness

**Comment by cmhchoi** [comment]
Still seeing it actually 

Can you try reproducing this please? @achilleas-kal

**Comment by achilleas-kal** [comment]
Hi @cmhchoi yeah there's an issue with the balances - reported it from community too here https://github.com/InjectiveLabs/injective-dex/issues/373 my balances on Mainnet seem normal so it doesn't happen with all the accounts not sure how to reproduce but I'll inform here if I find anything. Could be also related to https://github.com/InjectiveLabs/injective-dex/issues/414
