### ISSUE TITLE
TypeError in /derivatives/bnb-usdt-perp/

### ISSUE THREAD

**Issue by albertchon** [InjectiveLabs/injective-dex#422]
## Error in injective-dex

**TypeError** in **/derivatives/bnb-usdt-perp/**
Cannot read properties of undefined (reading 'makerPointsMultiplier')

[View on Bugsnag](https://app.bugsnag.com/injective-protocol/injective-dex/errors/619b44d98500910007b526bb?event_id=619b45b7008965eb74770000&i=gh&m=ci)

## Stacktrace

    components/partials/derivatives/trading/trade.vue?3f61:1180 - f.makerExpectedPts
    components/partials/derivatives/trading/trade.vue?6cf6:9 - f.<anonymous>

[View full stacktrace](https://app.bugsnag.com/injective-protocol/injective-dex/errors/619b44d98500910007b526bb?event_id=619b45b7008965eb74770000&i=gh&m=ci)

*Created by Bojan Angjelkoski via Bugsnag*

**Comment by albertchon** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/derivatives/bnb-usdt-perp/**](https://app.bugsnag.com/injective-protocol/injective-dex/errors/619b44d98500910007b526bb?event_id=619b45b7008965eb74770000&i=gh&m=fx)

**Comment by bangjelkoski** [comment]
Resolved https://github.com/InjectiveLabs/injective-dex/commit/e807614f45dfb099be966c8b980b2e1d77102629
