### ISSUE TITLE
Explicit market URLs don't work

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#435]
Explicit URLs like https://injective.exchange/spot/inj-usdt/ don't work.

![image](https://user-images.githubusercontent.com/83584143/143076998-54a541b9-fe75-49eb-aced-cf22f935f028.png)

Maybe related to #430 ? @bangjelkoski

**Comment by bangjelkoski** [comment]
I've added a potential fix and I couldn't reproduce the issue, so lets see how it behaves when we redeploy.
