### ISSUE TITLE
Balance Hold Increment

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#445]
Any ideas on this bug? @bangjelkoski 
![image](https://user-images.githubusercontent.com/83584143/143475225-2a4ea05a-c484-4b70-a070-5c17932a8f93.png)

**Comment by achilleas-kal** [comment]
Btw by Dyego:

  - I reduced the amount of INJ in the order a little, until the sum (total on ui + fees on UI) is less than my trading account balance. 
  - Only when the condition above is true, the order is actually being sent without errors.

**Comment by dyegonery** [comment]
Only to add some context to this issue, I spotted by using the "Max" button on the INJ Amount. So, I guess the actual amount being sent on the order is "Total" shown on UI + "fees". This causes the order being bigger than my balance.

**Comment by shane-moore** [comment]
hi @achilleas-kal & @dyegonery, do you still notice this issue? I successfully opened the limit market buy order shown below after setting an execution price of 4.000 USDT and selecting the 100% Max Amount

![Screen Shot 2022-01-23 at 5 47 03 PM](https://user-images.githubusercontent.com/41407272/150703228-69e5df51-135b-4f59-8440-81b14c17a553.png)

tagging @bangjelkoski for any additional input

**Comment by bangjelkoski** [comment]
It's quite hard to reproduce, but it still happens, yeah.

**Comment by dyegonery** [comment]
> hi @achilleas-kal & @dyegonery, do you still notice this issue? I successfully opened the limit market buy order shown below after setting an execution price of 4.000 USDT and selecting the 100% Max Amount
> 
> ![Screen Shot 2022-01-23 at 5 47 03 PM](https://user-images.githubusercontent.com/41407272/150703228-69e5df51-135b-4f59-8440-81b14c17a553.png)
> 
> tagging @bangjelkoski for any additional input

@shane-moore Yeah, it still happens. You just need  to select a market buy order, and click on "Max" amount. This will trigger the error every time, actually.

**Comment by bangjelkoski** [comment]
Resolved
