### ISSUE TITLE
MarkPrice Margin Requirement not properly handled

### ISSUE THREAD

**Issue by gorgos** [InjectiveLabs/injective-dex#446]
This error appeared despite having no warnings/validations in the UI.

![image](https://user-images.githubusercontent.com/659390/143507073-e4df88fd-24df-486e-ba3e-af4b854cfc67.png)

We have two checks for margin on-chain. Both should be handled properly in the frontend.

1. MarkPrice Margin Requirement

 - For Buys: `MarkPrice ≥ (Margin - Price * Quantity) / ((InitialMarginRatio - 1) * Quantity)`
 - For Sells: `MarkPrice ≤ (Margin + Price * Quantity) / ((InitialMarginRatio + 1) * Quantity)`

2. InitialMinMargin Requirement

`Margin ≥ InitialMarginRatio * Price * Quantity`, e.g., in a market with maximally 20x leverage, the initial margin ratio would be 0.05. Any new position will have a margin which is at least 0.05 of its notional.

**Comment by bangjelkoski** [comment]
Not a FE issue: https://github.com/InjectiveLabs/injective-exchange/issues/221
