### ISSUE TITLE
Checksum test failed

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#449]
I get this error when I try to connect my wallet, while being in the ATOM/USDT market.

If I go to a different market, connect the wallet and go back to ATOM/USDT I can trade normally.

![image](https://user-images.githubusercontent.com/83584143/143570309-4ce520f3-9120-432f-84ac-e3e565238216.png)

**Comment by bangjelkoski** [comment]
This should be resolved now after the latest `injective-exchange` has been deployed (it has to do with Chronos not being able to parse the ibc denoms properly).

**Comment by achilleas-kal** [comment]
Continues to happen.

![image](https://user-images.githubusercontent.com/83584143/144727143-bc2cb738-0457-4b3b-9fdb-8d94425841f2.png)

**Comment by bangjelkoski** [comment]
This is an issue on the `injective-exchange`, stored MongoDB markets were malformed for some reason so the guys manually updated them.
