### ISSUE TITLE
Ledger: object ProgressEvent

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#452]
Hey @bangjelkoski any ideas on the bug below? Connected natively with the ledger and trying to set an allowance

![image](https://user-images.githubusercontent.com/83584143/143658963-aa5fb510-612f-4558-8f99-163ae4eece6c.png)

**Comment by bangjelkoski** [comment]
I can't reproduce. We should first ask them to get the latest Ledger Live and firmware, clear cache and try again.
