### ISSUE TITLE
Markets tab loads when I click on a specific market

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#460]
When I click on a market on the homepage, as the market loads I also see the markets tab. This happens only the first time the DEX loads as shown in the video.

https://www.loom.com/share/16264ead573b42d280aafbc74adae592

**Comment by ThomasRalee** [comment]
resolved in [dff54081addf1f79f0100df61001f584b03eed51](https://github.com/InjectiveLabs/injective-dex/commit/dff54081addf1f79f0100df61001f584b03eed51)
