### ISSUE TITLE
Fee is shown based on mark price for market orders

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#502]
We shouldn't derive the fees based on the mark price but on the actual notional based on the orderbook.

![image](https://user-images.githubusercontent.com/83584143/146765777-834d9556-2795-4b96-8bc6-1fdfe90f1719.png)

**Comment by bangjelkoski** [comment]
We dont, we derive them from the orderbook.

**Comment by achilleas-kal** [comment]
Well here mark price is at 45,972.540 and I'm trying to buy 1 BTC.

The fee shown is 91.94508 which is 45,972.540 * 0.002 so it looks like it's based on mark price?
