### ISSUE TITLE
Invalid channel

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#506]
Happened when the user clicked "withdraw", can't replicate. This was fixed on his end after a refresh and he was able to withdraw the tokens to the bank balance.

![image](https://user-images.githubusercontent.com/83584143/147084130-b438e100-831b-4940-97b8-73435d71745f.png)

**Comment by bangjelkoski** [comment]
This is a server issue btw, it happens when the UI tries to reconnect to some stream but there is no response from the server.
