### ISSUE TITLE
[Market Page] Trading View - Bars

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#541]
The timeframe on the chart is set to 1 day and the bars at some point go from 20 Jan to 24 Jan opposed to 21 Jan. There are inconsistencies across the board and there's no pattern. It also went from Jan 9 to Jan 11 - so 2 days difference.

https://www.loom.com/share/3a6896bcd0134e968d71e4bd2a7e28b9

**Comment by Tofel** [comment]
So far I haven't seen the original issue mentioned (bars not shown), but what I've seen are extra bars that are rendered even though they shouldn't based on the interval selected. 

This screenshot shows the issue nicely. Selected interval is 2h and the candles from the past until page-opening-time are rendered correctly, every 2h. Going forward the problems appear and candle intervals become "random", sometimes they are rendered every minute, sometimes every couple of minutes.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/20401585/158187401-5861e210-9e27-44a5-a747-529b5abb3230.png">

Here the last correct candle was rendered at 00:56, then the next one rendered was rendered not for 02:56, but for 00:57. That screenshot was taken on March 2 9:44 (GMT-4) so it definitely shouldn't have that many candles rendered yet.

Now… I think the issue boils down to the values of query parameters we send to BE to obtain the data: https://api.injective.network/api/chronos/v1/derivative/history?symbol=BTC/USDT%20PERP&resolution=120&from=1646156762&to=1646228762&countBack=2

If you observe how from and to values change in time you'll see that if the user opened the chart exactly at 9:00, then from param would have the value of 13:00 of previous day and to param of 9:00 today. And BE would return data with correct internal.

But what would happen at 9:01? Well… from parameter would have value of 13:01 and to param of 9:01. And that will result in the char view rendering the candle for 9:01 even though the interval is set to 2h. Same thing happens every minute and that moving window results in printing candles for incorrect interval every time some data is returned.

I guess there could be many ways of tackling the issue depending on which component we can modify. Maybe we should do it the same way that Binance does? There candle start date doesn't depend neither on current time or user's local time, but always shows candles based on UCT time and anchors them in full hours:

- 1h → 00:00, 01:00
- 15m → 00:00, 00:15
- 2 → 00:00, 00:02

Thanks to that when using TR view on Binance candles are printed correctly regardless of the selected interval.

**Comment by Tofel** [comment]
all good ✅
