### ISSUE TITLE
[Homepage + Portfolio Page] Incorrect behaviour of the welcome banner

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#592]
**Steps to reproduce**
1. New account
2. Transfer some INJ to it while on portfolio page
3. Welcome banner will nicely indicate that you've deposited and now you should transfer to trading account
4. Transfer to trading account
5. Welcome banner will go back to original state (as if you haven't deposited anything)
6. Refresh
7. Welcome banner will disappear

**Expected result**
a. Banner doesn't go back to original state, once user user transfers funds to trading account, but shows correct state and next state (make a trade).
b. Banner doesn't disappear after page refresh, but only once user has executed a trade.

**Comment by bangjelkoski** [comment]
We just need to refresh the `onboarding` store module when we visit the homepage/portfolio page /cc @ThomasRalee
