### ISSUE TITLE
MAX field is misaligned in the market page [Safari Mac OS]

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#596]
![telegram-cloud-photo-size-1-4996846776044595782-y](https://user-images.githubusercontent.com/83584143/157859246-0af97ff4-1044-407d-ad35-826433b878f4.jpg)

![image](https://user-images.githubusercontent.com/83584143/157859275-231efc0a-d039-41f9-aa9c-206efecbb442.png)

**Comment by ThomasRalee** [comment]
Resolved in commit [44ad3579b0359077b6ac98fbfd9f03b6a78391e1](https://github.com/InjectiveLabs/injective-dex/commit/44ad3579b0359077b6ac98fbfd9f03b6a78391e1)

**Comment by bangjelkoski** [comment]
As per our discussion, minor issues don't need QA confirmation before deployment.
