### ISSUE TITLE
Streaming for Portfolio and Activity pages

### ISSUE THREAD

**Issue by cmhchoi** [InjectiveLabs/injective-dex#603]

**Comment by bangjelkoski** [comment]
We can have streaming for everything except for the PnL calculation for positions on the activity pages, they are hard to set up for streaming because we would need to track which positions are updated and then reset the market orderbooks stream, etc. We can poll this as we do it now.

**Comment by bangjelkoski** [comment]
Duplicate https://github.com/InjectiveLabs/injective-dex/issues/307
