### ISSUE TITLE
[Market Page] Do not show 'close all' button if there's nothing to close

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#610]
If we apply filtering and there are no positions/order that match it we shouldn't show the close all positions/orders button at all.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/20401585/158190919-5d52520a-2b25-48a6-8af7-12bde21696d9.png">

**Comment by bangjelkoski** [comment]
Note: When implementing, confirm that this is the case on the activities page as well.

**Comment by Tofel** [comment]
All good ✅
