### ISSUE TITLE
Handle wallet deletion / extension removal better

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#614]
**So here's the situation**
1. I have Keplr connected to DEX (probably same thing happens for MM).
2. I delete my Kelpr account / remove the extension all together.
3. I keep on surfing and using the site.

**What do I see?**
My wallet is still displayed as connected

I can try to deposit funds and, for example, trying to set allowance results in:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/20401585/158192300-5358dc1b-5625-4c5d-ac04-a2dfc5d35f67.png">

Maybe we could listen to that kind of event as account deletion and disconnect the wallet?

**Comment by bangjelkoski** [comment]
> **So here's the situation**
> 
> 1. I have Keplr connected to DEX (probably same thing happens for MM).
> 2. I delete my Kelpr account / remove the extension all together.
> 3. I keep on surfing and using the site.
> 
> **What do I see?** My wallet is still displayed as connected
> 
> I can try to deposit funds and, for example, trying to set allowance results in: <img alt="image" width="807" src="https://user-images.githubusercontent.com/20401585/158192300-5358dc1b-5625-4c5d-ac04-a2dfc5d35f67.png">
> 
> Maybe we could listen to that kind of event as account deletion and disconnect the wallet?

There are no such events emitted from any wallet, moving this to Glacier and we can revisit this once there is a support for this.
