### ISSUE TITLE
[Market Page] Replace dots on the chart with bars

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#626]
After I switch to new market on UI, as you can see on the right from historical trades, we have many trades in every 2 hours. However on the left, if we aggregate date points with 2h, it should NOT be just one dash line on the chart. It should be a bar. The issue can be resolved by switching between different time intervals for aggregation. But it leaves a pretty bad user impression, especially for new users.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/83584143/158220590-ce33c878-41a4-4120-a45e-1fef85518e92.png">

from @maximshen007

**Comment by maximshen007** [comment]
exactly, this issue has been existing for many months since we launched the mainnet. Thanks for cc me

**Comment by bangjelkoski** [comment]
This is resolved.
