### ISSUE TITLE
We are trimming decimals instead of rounding them on activity tab

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#647]
**Steps to reproduce**
1. Transfer any amount between wallet and trading account as long as you use a number with 4 digit precision that should be rounded up when displayed with 2 digits precision, e.g. `,2289`
2. Open activity -> wallet history -> transfers
3. Check amount transferred

**Expected result**
1. Decimal part is rounded to `,23`

**Actual result**
1. Instead of being rounded the amount is trimmed and displayed as `,22`

<img width="271" alt="image" src="https://user-images.githubusercontent.com/20401585/159302431-ec027483-7901-4f9a-9d7d-9b6c05e3f90b.png">

**Comment by ThomasRalee** [comment]
### Resolved in:
commit: https://github.com/InjectiveLabs/injective-dex/commit/3adaaf46bfea0a3c239f155819a5ee816f62bcf9

### Screenshots:
- #### Before (Trimmed off)
<img width="1418" alt="before" src="https://user-images.githubusercontent.com/10151054/162139540-77efad24-e7c9-4a97-9f49-f2a5db55f0d7.png">

- #### After (Round up/Round down)
<img width="1408" alt="after" src="https://user-images.githubusercontent.com/10151054/162139611-12c6dd8d-e62a-400e-81fc-59119c1d61f8.png">
