### ISSUE TITLE
[Market Page] - Total shouldn't be rounded

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#658]
Quantity * price here should be 426.023 and not 426. As per one of our MMs "the difference is huge for hft", the UI shouldn't round up the number.

If we round it in the "Activity" page too we should fix there as well.

![telegram-cloud-document-5-6194891451420116646](https://user-images.githubusercontent.com/83584143/160235610-1c20cb61-09a1-47c1-b3e4-059c68b07119.jpg)

**Comment by maximshen007** [comment]
Just a side note, traders should reply on API for full data granularity. UI display should just be for display purposes. Later on, when we create our own trading mobile app, this display "issue" should be ignored, IMO. This should be categorized as enhancement

**Comment by achilleas-kal** [comment]
Sure, fair enough but if they thought it's a bug that should be reported others might as well would be good to display the full amount in this case, they constantly use the UI to verify txs.

**Comment by achilleas-kal** [comment]
This is actually correct, the order was posted at 42,600 but was traded at 42,602.3 so 42,600 * 0.01 matches the total returned from the BE.

Closing the issue.
