### ISSUE TITLE
Do not uncheck "hide minimal balances" after performing transfer/deposit/withdrawal operations

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#671]
Currently if I have that checkbox checked and I make a transfer between wallet and trading account once that operation has been completed my checkbox gets automatically unchecked. Maybe it would make more sense to keep it checked until user navigates away from the page or unchecks it manually?

Steps:
1. Go to Portfolio page.
2. Select "hide small balances".
3. Transfer some funds to trading account & sign the message.
4. Click "OK" to close the popup with confirmation.
5. Observe filtering applied to assets table.

**Comment by bangjelkoski** [comment]
To be honest, we shouldn't refresh the whole table when we do some transfer, instead, we should only refresh that particular row within the table with the updated balance.

**Comment by Tofel** [comment]
That would solve the issue.

**Comment by ThomasRalee** [comment]
Resolve in commit https://github.com/InjectiveLabs/injective-dex/commit/844317d3cf4dec1e2ef4a1de6d08642c9e0b97f5
