### ISSUE TITLE
[Standalone Market Page] Exclude token name when sorting by numeric values [low prio]

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#706]
**Steps to reproduce**
1. Open standalone market page.
2. Filter by COMOS (or any other filter for which all positions have `0` value for some column)
3. Filter by that numeric value (e.g. by Volume if all of them have 0 volume)
4. Change filtering direction.

**Expected behaviour**
1. Order of entries doesn't change.

**Actual behaviour**
1. Order of entries does change, most probably, because the token name also used by sorting function (so that `0.0000 ATOM` is evaluated as "higher" value than `0.0000 LUNA`)

![image](https://user-images.githubusercontent.com/20401585/163977753-82a4ff81-bc8a-45d3-ba53-d88826579d78.png)
![image](https://user-images.githubusercontent.com/20401585/163977835-12725692-0081-47a2-87bf-eb6a451a2109.png)

**Comment by ThomasRalee** [comment]
Hi @Tofel, can you share the ideal/expected UX for this?
- sort by volume then alphabetically?

**Comment by terencetang9** [comment]
This issue can be omitted - we shouldn't have zero volume markets in reality. 

This behaviour is acceptable and very rare we will run into this.

**Comment by Tofel** [comment]
Yeah, shouldn't happen on prod. If it does we are in trouble!
