### ISSUE TITLE
[Standalone Market Page] Missing search icon for free text search input [low prio]

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#708]
**Steps to reproduce**
1. Open standalone market page
2. Filter by custom text
3. Observe the search input

**Expected results**
1. Once something in typed in to the input the (x) icon is displayed allowing the user to clear the input
![image](https://user-images.githubusercontent.com/20401585/163981041-2466c777-99a0-45f0-9117-19c8552dc5ca.png)

**Actual results**
1. No such icon is displayed
![image](https://user-images.githubusercontent.com/20401585/163980982-492bc889-72c1-4c40-9adf-bff659d45585.png)

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/fd888ee075d41b54cfa8905e14406a4a4d9d4ca6

**Comment by terencetang9** [comment]
Verified in devnet
