### ISSUE TITLE
[Standalone Market Page] Volume calculation in base asset

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#709]
I wonder whether we calculate the trading volume correctly. Please look at steps and expectations and let me know if I'm missing something.

**Steps to reproduce**
1. Find a market that has no trades at all.
2. Login as 2 users in separate browsers.
3. Create some resting orders as user 1.
4. Place some market orders as user 2 (so that trades are placed immediately).
5. Compare volume data on market's page and on trading view. Focus on the volume.

**Expected results**
1. Data on market page matches data on trading page (especially volume in base asset).

**Actual results**
GF volume is equal to 6 GF,
![image](https://user-images.githubusercontent.com/20401585/163988484-f26bb73a-3317-40b0-bf2b-b771aeae67a8.png)
but in reality only 5 GF were traded
![image](https://user-images.githubusercontent.com/20401585/163988549-f735d753-3a81-4435-b56c-b36832896a8a.png)

Instead of using the real volume in base currency are we basically dividing volume in quote currency by last traded price? `18 USDT / 3 USDT = 6 GF`? And if that's what we do, is it what we should be doing?

**Comment by terencetang9** [comment]
Good catch - after evaluating the issue further we have decided to show the volume in quote currency instead.

This issue can be closed once the volume unit has been updated to quote currency.

**Comment by bangjelkoski** [comment]
@ThomasRalee

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/fd888ee075d41b54cfa8905e14406a4a4d9d4ca6

**Comment by Tofel** [comment]
Good to go ✅
