### ISSUE TITLE
[DEX] Market search should not be case sensitive [med prio]

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#711]
### **Steps to Reproduce**
Environment: Devnet
1. Go to /markets or market selection dropdown on trading UI
2. Focus on search bar
3. Provide search input with some character(s) in uppercase
4. Observe

### **Actual Results**
Assuming the search input is `BTC` or `bTC.` There is no matching market returned despite `BTC/USDT PERP` is listed. The search criteria is case sensitive. `BTC/USDT PERP` is only returned if the input is `btc`.

### **Expected Results**
The search criteria should not be case sensitive.

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/762c657ce97b508be474db4e6e4f7c260758cf40

**Comment by terencetang9** [comment]
Verified in devnet
