### ISSUE TITLE
[Market Page] - Trade price colours differ 

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#715]
Occasionally the colours for the last traded price on the top are opposite which is confusing.

![Pasted Graphic 1](https://user-images.githubusercontent.com/83584143/164193153-ae10dd29-229c-4db6-9a2f-636f70789cbd.png)

1) We had buys but on top it shows red (negative)
![Pasted Graphic 2](https://user-images.githubusercontent.com/83584143/164192918-34340f3c-9bae-42e3-9f19-30c847dcbe3e.png)

2) Here it shows correctly
![Pasted Graphic 4](https://user-images.githubusercontent.com/83584143/164193031-452e1292-1476-4784-946e-975b58c7da3f.png)

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/6e04d6932d72a8ef9e5aeefaf8928295386b58c6

**Comment by achilleas-kal** [comment]
1. When the trade is a buy, the trade price and the arrow show green (as expected)
![image](https://user-images.githubusercontent.com/83584143/167123631-62f6a322-87e6-470c-a4f1-eb92b8f4e6ba.png)

2. When the trade is a sell, the trade price shows green and the arrow shows red (we should see red for both)
![image](https://user-images.githubusercontent.com/83584143/167123642-d6757493-dbb1-4b14-99a9-2bb3d2d562e1.png)


cc @ThomasRalee

**Comment by achilleas-kal** [comment]
Fixed now, thanks @ThomasRalee!
