### ISSUE TITLE
[Market Standalone Page] - Redirect links for BAYC/WETH PERP

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#716]
![image](https://user-images.githubusercontent.com/83584143/164193562-60d8db1a-0bad-42ec-9baf-d8c1458dc851.png)

The links here supposedly redirect to burnt.com and nftbank.ai but if you click on them you're redirect to the market page and not the websites - is that intended?

**Comment by terencetang9** [comment]
It should redirect the users to burnt.com / nftbank.ai

**Comment by terencetang9** [comment]
Already resolved
