### ISSUE TITLE
[Market Page] - Consistency in decimals for last traded price

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#717]
The last traded price on top (42,683.5360) should be 42,683.536 to have consistency with the price we show in the orderbook.

![image](https://user-images.githubusercontent.com/83584143/164194818-eb7e84f5-c56b-4730-a0e3-2d9b6a306823.png)

Binance
![image](https://user-images.githubusercontent.com/83584143/164194858-5706f811-fed5-4a37-9801-562e764472de.png)

**Comment by terencetang9** [comment]
Resolved
