### ISSUE TITLE
[Market Standalone Page] - Missing symbols

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#726]
The symbols were replaced by the "favorite" icon, if we only have space for one I think symbol is way more important than favorite but ideally we can accommodate both.

![image](https://user-images.githubusercontent.com/83584143/164262457-06523741-be40-4c74-8bcd-e91b1d0af97f.png)

**Comment by terencetang9** [comment]
@achilleas-kal Yeah ideally to show both bookmark icon and coin logo. Let's go with this version first and see what our users say. 

I did a quick accessibility testing and found out that we might have enough space for coin logo. Can do this in next iteration.
