### ISSUE TITLE
[DEX] Chart, Orderbook and Recent Trades To Be Grouped into Tabs in Mobile Viewport

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#740]
### **Design**
- [Grouped Tabs](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=4165%3A8547)

![image.png](https://images.zenhubusercontent.com/624fe18ce7c8d38e2586ee14/8943513a-cb37-41f7-b93e-65226ed48748)

### **Summary**
- [ ] Candlestick chart, orderbook, and recent trades should be grouped together under tabs
- [ ] By default users will be on candlestick chart tab
- [ ] Users can switch to view between candlestick chart, orderbook, or recent trades

**Comment by terencetang9** [comment]
@ThomasRalee Orderbook restyling not part of this scope.

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/a03d98479d6c1246f016069b7ef6f8440c3e937f

## Screenshots:
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/10151054/167082843-1b15d2e6-0175-4eda-b412-de420dbaeb73.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/10151054/167083402-7c7b27ef-c493-4408-a2f9-7f81b502a133.png">
