### ISSUE TITLE
[DEX] [Markets] Show filter parameters in URL

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#741]
### **Summary**
- [ ] Show filter parameters in the URL as the user filters the standalone markets page with market type, quote currency, and category

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/ba4dfe9cad0cb879af61b2da9d3691fd2fb585f2
