### ISSUE TITLE
[Market Page] - Market sells show incorrect amount order details

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#746]
### **Summary**
Use average price with default slippage to calculate order details and also order input for a market order. 

### **Actual Behaviour**
Lowest bid in the orderbook that will be filled by a market order is being used as the worst price and using it as the "worst price" for the calculations but that's not what will actually happen on-chain.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/83584143/164892580-de835f2d-9082-4406-8980-382b6c3693f3.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/83584143/164892586-ea3a887e-b5a6-4c8d-8ac9-4f2fc4994523.png">

### **Expected Behaviour**
Use average price to calculate the total cost of the market order (order amount * average price + fee).

**Comment by achilleas-kal** [comment]
Looks like here we're taking the lowest bid in the book (that will be filled by my market order) and using it as the "worst price" for the calculations but that's not what will actually happen on-chain.

I think we should use the average price instead since my market order will fill those resting orders at their specified price. 

![image](https://user-images.githubusercontent.com/83584143/165362906-59188962-0621-414d-8516-6d36c8e35419.png)

For instance, here we use the bid at 0.015 for the calculations instead of 1.490 (average price) and this implies that the market order will be filled for my total amount at 0.015.

Could you share your thoughts as well? @bangjelkoski

**Comment by Tofel** [comment]
looks good ✅
