### ISSUE TITLE
[DEX] Incorrect welcome banner's behaviour

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#747]
**Steps to reproduce**
1. Connect a fresh wallet.
2. Deposit some funds and transfer them to trading account.
3. Open portfolio page and observe welcome banner.

**Expected results**
1. Welcome banner is shown.
2. It displays info that user is on the 3rd step of onboarding, which is trade.

**Actual result**
1. Welcome banner is nowhere to be seen.

Remember that it should disappear only after user makes her first trade, not before.

**Comment by ThomasRalee** [comment]
Resolve in commit https://github.com/InjectiveLabs/injective-dex/commit/cf8be994a023cef290eff14aca90b8199eb27441

### Screenshot:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/10151054/166740231-43a4c0b6-bb75-4c1d-b080-1b3ef84358e9.png">
