### ISSUE TITLE
[Torus] Increase balance fetching timeout and/or modify the error message

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#749]
I won't give you the exact steps to reproduce as I was unable to reproduce it, but I remember what and how it happened. For whatever reason Torus was responding slower then usual and then I tried to sign a transaction before its details even loaded in a new window I saw an error message like this one:
![image](https://user-images.githubusercontent.com/20401585/165063532-3d9a5e92-2e30-433f-bb84-efe0ef85967f.png)
And the console said that balance fetching couldn't be completed in 5 seconds.

Maybe it would be wise to:
* increase that timeout
* modify the error message to actually mention timeout and not signature rejection

**Comment by bangjelkoski** [comment]
This is coming from Torus tho, it's not something that we can control. Maybe we can handle the error more gracefully, but I don't know whether changing error responses from Wallets make sense at this point.
