### ISSUE TITLE
Deposit and Withdrawal history not showing Injective to Injective transactions

### ISSUE THREAD

**Issue by cmhchoi** [InjectiveLabs/injective-dex#751]
![Screenshot 2022-04-26 at 4.31.39 AM.png](https://images.zenhubusercontent.com/6228552ed06a423810cb6a41/11e6b59b-08b4-44ba-a5b9-a3fca5c070bd)

Expectation:
The deposit history should also include this transaction: https://explorer.injective.network/transaction/CE07B7BE0D0C5B655DB6B1BC735D6A7B6FF5D6D5D07CE6F557DDB6951EB2BE8A

**Comment by achilleas-kal** [comment]
@cmhchoi wouldn't this be expected to show under "Transfers" since it's an on-chain transfer?

To my knowledge Deposits/Withdrawals show only transfers between Injective and other chains (ETH/IBC) as per the initial implementation.

**Comment by terencetang9** [comment]
@ThomasRalee @achilleas-kal Chris and I both think that it will be better to place these transactions in the `Deposits` and `Withdrawals` sections. `Transfers` should be showing only the funds transfers between bank module and trading account.

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/93c59aba41a38ffa5df0422f007aac9004d4714b

### Screenshots:
![image.png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/e95ea6c1-8e6e-4aaa-b8b7-d848e3dfcc65)
![image.png](https://images.zenhubusercontent.com/5c78b09a667fa90f63785dbb/d31c420d-c306-4c87-a436-61e24b5d5c29)

**Comment by achilleas-kal** [comment]
Fixed
