### ISSUE TITLE
[Market Page] - Keep asset persistent on tab view

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#754]
I think the tab on top should show the asset of the market I'm currently in rather than change to different markets all the time. Traders usually have open tabs for markets they have open positions/orders or just for markets they want to track across different exchanges so we should not change them imo.

For instance here I'm in ATOM/USDT PERP but I see the INJ/USDT PERP price on the tab.

<img width="1892" alt="image" src="https://user-images.githubusercontent.com/83584143/165288885-164c7c28-9e7d-4a33-8923-2df90ce754ad.png">

**Comment by terencetang9** [comment]
@Tofel For your reference as well

**Comment by achilleas-kal** [comment]
Fixed
