### ISSUE TITLE
[Other] - Modify the routes config to show all markets on-chain by default for specific networks

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#755]
Apart from the obvious networks (`testnet` & `devnet`) I think it would be very helpful for `staging` as well so we can easily test new markets and also be able to QA markets that will be visible on other relayers in the future but not on injective.exchange. Having a UI to show all markets in prod could come handy.

**Comment by bangjelkoski** [comment]
Not possible at the moment, it might be once we start the `lists` approach that Chris suggested.
