### ISSUE TITLE
[Market Page] - Mark price colour

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#756]
### **Summary**
- [ ] Show mark price in neutral white color without any color coding logic based on tick direction

### **Actual Behaviour**
![image](https://user-images.githubusercontent.com/83584143/165503445-472a6f81-2f32-43b4-8da1-1fdaf38a11d9.png)

**Comment by achilleas-kal** [comment]
![image](https://user-images.githubusercontent.com/83584143/165504072-a047d230-1c7b-4c61-a28a-8e7e750430a7.png)

I also think it would be better to change the ordering between the est. funding rate and funding interval so that the coloured field (est. funding rate) is last and there's some consistency.

**Comment by terencetang9** [comment]
@achilleas-kal  Good call out on the mark price color coding.

**Comment by terencetang9** [comment]
@ThomasRalee  We will keep the ordering - only need to change mark price color to neutral white (i.e. no green / red color change).

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/f08a6fd0bd19ebf0409b998c03011d3d72223d93
