### ISSUE TITLE
[Market Page] - The indicator showing that an order is mine shows only after a refresh

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#765]
**Describe the bug**
The arrow indicating that the resting order is mine appears only after a refresh.

**To Reproduce**
Simply place a limit order, notice that the "arrow" showing that the order is yours is not there. Refresh.

**Expected behavior**
We should see the arrow pointing to my order the moment I submit it.

**Screenshots**
![image](https://user-images.githubusercontent.com/83584143/165916754-f6255c06-7544-4565-abdc-99981e18f9f9.png)

![image](https://user-images.githubusercontent.com/83584143/165916781-bd78606c-ab6c-4807-8bd9-49fc83c4522a.png)

**Additional context/device information**

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/c25c4a9aab5bd90603f44cc9b53e62cc08d7a239
