### ISSUE TITLE
[Portfolio Page] - IBC assets do not need allowance

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#767]
**Describe the bug**
EVMOS shows an "allowance", since it's an IBC denom that will have its own bridge we should show the same message as we do for other cosmos-based assets and redirect people to the hub. Thus, we need to add "EVMOS" in the network options and show this message for the EVMOS Asset.

**Screenshots**
![image](https://user-images.githubusercontent.com/83584143/165927659-a7acb659-0720-4bc2-a159-678b9953c6ab.png)

![image](https://user-images.githubusercontent.com/83584143/165927785-fa57c840-fcbc-4d76-a49a-74024f24a46b.png)

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/e09ddc5e4d9d1970f9e39b6a267d49a12a4c1ae7, pushed fix to staging

**Comment by achilleas-kal** [comment]
Fixed
