### ISSUE TITLE
[DEX] Favorites link is broken on trading view

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#770]
**Describe the bug**
Impossible to access favorites section on the trading view on the slide-in markets widget.

**To Reproduce**
1. Just click on the star icon and observe that "nothing happens" and you got a nice error in the console.

**Expected behavior**
You know it better than I! ;-)

**Screenshots**
![image](https://user-images.githubusercontent.com/20401585/166206366-8e89db10-49ad-43bf-bfe7-131c130453bf.png)

**Comment by ThomasRalee** [comment]
Resolve in commit https://github.com/InjectiveLabs/injective-dex/commit/1d50e99e719d54d2c3d7a81de6cbdefdd7992211

**Comment by Tofel** [comment]
All good ✅

**Comment by terencetang9** [comment]
@ThomasRalee @Tofel Is this fix pushed to production yet?
