### ISSUE TITLE
[DEX] [Markets] "WHAT'S NEW" Highlighted Market Is Not Showing Latest Listing

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#772]
### **Steps to Reproduce**
1. Go to https://injective.exchange/markets/
2. Check the highlighted markets at the top
3. Check "WHAT'S NEW" market specifically

### **Actual Behaviour**
Currently EVMOS/USDT should be the latest listing (as of 3 May 2022) but BAYC/WETH PERP is shown instead.
![image.png](https://images.zenhubusercontent.com/624fe18ce7c8d38e2586ee14/d881856b-fdd0-437b-a55f-065125eca20e)

### **Expected Behaviour**
Latest listing should be shown, i.e. EVMOS/USDT.

**Comment by terencetang9** [comment]
CC: @Tofel

**Comment by ThomasRalee** [comment]
Closing this issue, as it has been resolved on the dev branch, the fix will be reflected on prod once we merge the latest changes.
