### ISSUE TITLE
[DEX] Use Mark Price to Calculate Unrealized PNL for Open Positions

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#783]
### **Summary**
- [ ] Change to use mark price to calculate unrealized PNL for open positions

**Comment by ThomasRalee** [comment]
Resolved in [PR](https://github.com/InjectiveLabs/injective-dex/pull/785).

**Comment by Tofel** [comment]
all good!

**Comment by Tofel** [comment]
all good!
