### ISSUE TITLE
[DEX] [Markets] Logic Update for Top Gainer

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#793]
### **Summary**
On /markets page, we enhance the display logic for the **Top Gainer** such that
- [ ] If the last price is 0, then the market is not eligible to be the top gainer.
- [ ] If the top gainer happens to the one with zero last price, show the subsequent one with non-zero last price.

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/a152ba16dc1ec028bef5b4c64fb6e4aea767b1af

**Comment by Tofel** [comment]
looks good! ✅ 

and if there's no market with last traded price <> 0 the card is not displayed at all.

**Comment by ThomasRalee** [comment]
> and if there's no market with last traded price <> 0 the card is not displayed at all.
That's the UX by implementation, this probably won't happen on prod, not having any market with last traded price > 0.

@terencetang9 can you please confirm?

**Comment by terencetang9** [comment]
Yeap - that's shouldn't happen in production environment.
