### ISSUE TITLE
[DEX] [Trade] Deprecate LUNA/UST and LUNA/UST PERP

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#795]
### **Summary**
- [ ] Users can no longer trade LUNA/UST and LUNA/UST PERP on Injective Pro
- [ ] Users can still access the trading page but with a modal dialogue that states that the market is no longer tradable and also Terra bridge is currently disabled

### **References**
https://app.zenhub.com/workspaces/product-engineering-team-6228558038ca2f002011c6a3/issues/injectivelabs/injective-dex/790
https://app.zenhub.com/workspaces/product-engineering-team-6228558038ca2f002011c6a3/issues/injectivelabs/injective-hub/538

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/pull/796/commits/2bff368271b11c9493e97bd0fe483e99b2bf171a
