### ISSUE TITLE
[DEX] [Trade] Reduce-Only Order Placement Of A Market Should Not Be Impacted By Other Markets

### ISSUE THREAD

**Issue by terencetang9** [InjectiveLabs/injective-dex#813]
### **Steps to Reproduce**
1. Have open positions
2. Have reduce-only open orders
3. For a given open position of a market that doesn't have reduce-only open order, try to input a reduce-only order by tapping **[MAX]**
4. Observe

### **Actual Behaviour**
- The amount input via **[MAX]** is not equivalent to the amount of corresponding open position that is supposed to be closed by the intended reduce-only order.
- The amount input is impacted by the reduce-only open orders of other markets (i.e. in some scenarios the input number is negative which is not correct)

### **Expected Behaviour**
- We have yet to support portfolio or cross margin. The amount input for reduce-only orders of a given market shall be independent of other unrelated markets (i.e. ETH/USDT PERP reduce only orders should not be impacted by BTC/USDT PERP reduce-only orders)

**Comment by ThomasRalee** [comment]
Resolved in commit https://github.com/InjectiveLabs/injective-dex/commit/b252f4605bb44af9e99f8c5dd4c145b5343750f7
