### ISSUE TITLE
Incorrect z-index for side dropdown on trading account / open positions

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#816]
**To Reproduce**
1. Open trading account for user without any positions
2. Click on the "side" dropdown

**Expected behavior**
All options of the drop down are visible.

**Screenshots**
<img width="475" alt="image" src="https://user-images.githubusercontent.com/20401585/169693272-aa92ec16-668c-46c9-bc65-ede22b90002c.png">

**Comment by shane-moore** [comment]
this seems to be working fine now so I'm closing unless the issue reappears
