### ISSUE TITLE
[Homepage] - Misaligned logo

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#854]
**Describe the bug**
The logo is misaligned.

**Screenshots**
![telegram-cloud-photo-size-1-4958585996191050395-y](https://user-images.githubusercontent.com/83584143/171901722-2b315745-2d1e-49ac-9908-2a9e0afda66d.jpg)

![telegram-cloud-photo-size-1-4958585996191050393-y](https://user-images.githubusercontent.com/83584143/171901732-6f9d2386-8267-4d85-a40f-dc3579bd9523.jpg)

**Comment by ThomasRalee** [comment]
Cannot replicate.
