### ISSUE TITLE
[Market Page] - Average Price

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#859]
**Describe the bug**
My order here will be filled at 31,000, there's no average price since it will fill only a single order at TOB. Also, how is average price calculated? We should calculate it based on the orders that will be filled based on my price/quantity which seems not to be the case here.

**Screenshots**
![image](https://user-images.githubusercontent.com/83584143/172165038-515d2079-6287-456b-ad12-51dccecd0168.png)

**Comment by terencetang9** [comment]
This is correct - currently it has 0.5% slippage applied so the average price is 31,000 * 0.995 = 30,876.

We will change this and remove slippage from average price calculation (both spot and derivatives). For spot the user will be able to see worst case where slippage is applied if indicated.
