### ISSUE TITLE
DEX's trading component not showing taker fee discount for markets with negative maker fee

### ISSUE THREAD

**Issue by Tofel** [InjectiveLabs/injective-dex#866]
Taker's trade preview (no discount applied):
<img width="211" alt="image" src="https://user-images.githubusercontent.com/20401585/172680937-bef72ef2-c6f3-46a8-82a9-959f652bdf8e.png">

Discount tier:
```
{
  "tier_level": "1",
  "account_info": {
    "maker_discount_rate": "0.500000000000000000",
    "taker_discount_rate": "0.500000000000000000",
    "staked_amount": "1000000000000000000000",
    "volume": "40000000000.000000000000000000"
  },
  "account_ttl": {
    "tier": "1",
    "ttl_timestamp": "1654709303"
  }
}
```

Market info:
```
      {
        "ticker": "BNB/USDT",
        "base_denom": "peggy0xB8c77482e45F1F44dE1745F52C74426C631bDD52",
        "quote_denom": "peggy0xdAC17F958D2ee523a2206206994597C13D831ec7",
        "maker_fee_rate": "-0.000100000000000000",
        "taker_fee_rate": "0.002000000000000000",
        "relayer_fee_share_rate": "0.400000000000000000",
        "market_id": "0x74b17b0d6855feba39f1f7ab1e8bad0363bd510ee1dcc74e40c2adfe1502f781",
        "status": "Active",
        "min_price_tick_size": "0.000000000000001000",
        "min_quantity_tick_size": "1000000000000000.000000000000000000"
      },
```

Actually charged fee:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/20401585/172681547-d4820f1c-5fca-474b-8994-dfeb2c5bb143.png">

Summary:
Trading component shows that taker will be charged the full fee, but what really happens is that he's charged the discounted one (50% of 0,02%).

**Comment by achilleas-kal** [comment]
Duplicate: https://github.com/InjectiveLabs/injective-dex/issues/862

**Comment by Tofel** [comment]
@achilleas-kal  How is that related to volume? It doesn't matter why user has a discount. It only matters whether market has positive or negative maker fee. On markets with positive maker fee I see it rendered correctly.

**Comment by achilleas-kal** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/83584143/172685951-5fd667ef-1706-401f-bba3-c01523252c0d.png">

<img width="826" alt="image" src="https://user-images.githubusercontent.com/83584143/172685999-14eb5ebc-a3dd-4498-abdc-f8faafe2ee10.png">

**Comment by achilleas-kal** [comment]
It's not related, just pointing out that the previous ticket mentions that we need to fetch the Tier/decrease fees accordingly in the market page - volume was a different point but they are both related to fee discounts.

**Comment by terencetang9** [comment]
We need to remove the special handling that on the taker side fee discount will still be applicable even if maker fee is negative.
