### ISSUE TITLE
[Wallet History] - Add Evmos in the networks 

### ISSUE THREAD

**Issue by ThomasRalee** [InjectiveLabs/injective-dex#905]
**Describe the bug**
We should add Evmos to the networks, this is not an Ethereum > Injective transfer, should be Evmos > Injective.

**Screenshots**
<img width="1828" alt="image" src="https://user-images.githubusercontent.com/83584143/173325148-c4f12037-71ba-4dc3-8ef5-b9fa802d889d.png">

Duplicate issue transferred from [Hub](https://github.com/InjectiveLabs/injective-hub/issues/594)

**Comment by achilleas-kal** [comment]
Fixed
