### ISSUE TITLE
VIP Tier Percentages are incorrect in the navbar dropdown

### ISSUE THREAD

**Issue by dyegonery** [InjectiveLabs/injective-dex#973]
**Describe the bug**
I have an account which is on the Tier 1 of the Vip Program. On the fee-discounts page, my account is being shown as under Tier 1 (which is correct). But, in the dropdown activated when we hover the account address (top right corner), the percentages are being presented incorrectly. 

**To Reproduce**
I believe this problem is only happening if the given account is at least under the Tier 1 of the VIP program. In this case, just open the dropdown on the top right corner of the page by hovering the mouse on the account address.

**Screenshots**
![Screenshot from 2022-09-19 18-25-08](https://user-images.githubusercontent.com/4934602/191122975-e5723ca7-28ef-4032-85ec-55bb973c1739.png)
![Screenshot from 2022-09-19 18-24-37](https://user-images.githubusercontent.com/4934602/191122978-4d4f316e-6cbe-4627-b414-078201065e70.png)

**Comment by dyegonery** [comment]
Just to confirm, although this issue has been closed, I can confirm it's still happening on my end.

**Comment by bangjelkoski** [comment]
cc @afterburn
