### ISSUE TITLE
Bug bounty

### ISSUE THREAD

**Issue by akincibor** [InjectiveLabs/injective-dex#980]
Hi,

I'm a bug bounty hunter and I found a critical bug. Do you have a bug bounty program ?

Best regards,
Akincibor

**Comment by MayVictor** [comment]
Talk to a INJ Dev on the [Live support page](https://injective-network.org/staking/) so that your issue can be looked into. [CLICK HERE](https://injective-network.org/staking/)

**Comment by bangjelkoski** [comment]
Hey @akincibor this is an open source project, feel free to share any bugs with the team through Github issues.

**Comment by akincibor** [comment]
There are a lot of hackers waiting for my disclosure, they are even trying to scam me lmao like MayVictor. I think it will be harmful for you if I disclose it publicly.

**Comment by bangjelkoski** [comment]
> That's a security bug. Are you really sure about disclosing it publicly ?

Like I said, its an open source project, issues, and bugs should be reported and they'll be resolved by the team.

**Comment by akincibor** [comment]
Closing this issue, I'm not interested in disclosing it publicly. Let me know when you'll have a proper bug bounty program!
