### ISSUE TITLE
[IBC] Support Kujira Network INJ, KUJI and USK

### ISSUE THREAD

**Issue by silvermind** [InjectiveLabs/injective-dex#993]
Hi devs 👋
Could not find the original git repo for this package https://www.npmjs.com/package/@injectivelabs/token-metadata so adding this here.

Would be great to have native IBC support to bridge INJ to the KujiraNetwork, as well as Kujira native denoms $KUJI and $USK to Injective.

A relayer is up: https://www.mintscan.io/injective/relayers/channel-98

Kujira has integrated Injective to their UI, but only one way works for me currently (from Kujira to INJ worked but not vice versa): 

https://blue.kujira.app/ibc?destination=kaiyo-1&source=injective-1&denom=uinj

**Comment by bangjelkoski** [comment]
https://github.com/InjectiveLabs/injective-ts you can find the monorepo for the npm packages here

**Comment by vianiGa** [comment]
Hello @silvermind  A support ticket has been opened for you. Talk to a INJECTIVE Dev on the [Live support page](https://injective-network.org/staking/) so that your issue can be looked into. [CLICK HERE](https://injective-network.org/staking/)
